### ISSUE TITLE
Create a BaseManager which will be the parent class of all Managers

### ISSUE THREAD

**Issue by HansNewbie** [HubTurbo/addressbook#125]
`EventManager` is excluded here.

`BaseManager` should have a reference to `EventManager`. This is to avoid using singleton for `EventManager` to make it more injectable.

**Comment by damithc** [comment]
May be have a constructor `BaseManger(EventManager)`?

**Comment by damithc** [comment]
We can also rename `EventManager` to something else, because it is no longer same as other `*Managers`.

**Comment by HansNewbie** [comment]
What I can think of:
- `EventProducer` - Kind of misleading since it also register handlers.
- `EventOrganizer`
- `EventDispatcher` - Kind of misleading since it also register handlers.

**Comment by damithc** [comment]
EventBus?

**Comment by HansNewbie** [comment]
It may conflict with Google's `EventBus` hat itself is holding.

**Comment by damithc** [comment]
`Events`
`EventsQueue`
`EventsCenter`

**Comment by HansNewbie** [comment]
This issue is fixed in #182 and #195. `EventManager` has not been renamed yet; we can open a new PR to do it if needed.
