### ISSUE TITLE
Look into UI enhancement.

### ISSUE THREAD

**Issue by yl-coder** [HubTurbo/addressbook#140]
Especially Listview.
For example,
when a person is deleted, can we have diminishing effects?

**Comment by yl-coder** [comment]
Refer to branch [#140-look-into-ui-enhancement](https://github.com/HubTurbo/addressbook/tree/140-look-into-ui-enhancement)

**Comment by damithc** [comment]
But first, try to clean up the UI. alignments, responsiveness, styling etc. At some point we even lost the original dark theme the address book had

**Comment by yl-coder** [comment]
Right, we fix it.
