### ISSUE TITLE
Increase flexibility of failure manipulation in the cloud simulator

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#215]
So that we can easily indicate when and where it should fail when required.

**Comment by m133225** [comment]
@damithc Do you have any examples for this? This functionality seems rather vague.

**Comment by damithc** [comment]
Need to look at the code to give a more specific answer. More generally, we should be able to trigger operations in sync and cloud simulator at anytime we wish and if those operations can fail in different ways, we should be able to trigger a specific failure anytime we want.

**Comment by m133225** [comment]
Is this only meant for integration testing? If it is, then I think a `mock` might achieve the same result.

Outside of integration testing, it may be difficult to trigger failure at "anytime" unless there is a GUI for us (e.g. list of buttons, or at least some kind of hotkey) to use to activate these failures.

**Comment by damithc** [comment]
Yes, for testing. A mock is fine if that works.

**Comment by damithc** [comment]
Closing, as we are working on this in other PRs.
