### ISSUE TITLE
File->New is broken

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#23]
`UnsupportedOperationException` from [line 35](https://github.com/HubTurbo/addressbook/blob/a409ff66a17decdc33761e73ccaa7a69ecbffd4c/src/main/java/address/controller/RootLayoutController.java#L35) in `RootLayoutController`.

The object returned by `getPersonData` is a `FilteredList` which does not support `clear`. Same problem as #16.

**Comment by damithc** [comment]
@YijinL Are you fixing this? Get the issue assigned to you if you are working on it.

**Comment by YijinL** [comment]
Yes; should I be added to the members so I can do the self-assignments and merging etc?

**Comment by damithc** [comment]
Invite sent
