### ISSUE TITLE
person edit dialog: enable tab order

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#232]
Enable tab order for the input fields

**Comment by m133225** [comment]
Isn't this behaviour (cycling through input fields using tab) already present by default? Seems to work fine for me.

**Comment by damithc** [comment]
Yes, seems to work, but may be set the focus to one of the input boxes at the beginning? 
Also, can we get make ESC dismiss the dialog?

**Comment by yl-coder** [comment]
Yes we can.
