### ISSUE TITLE
Move file location to footer

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#233]
This can be moved to the footer (periodic status bar). This space is for the action status bar.
![image](https://cloud.githubusercontent.com/assets/1673303/16105355/3421b6c6-33bc-11e6-9475-810416c297d1.png)

**Comment by yl-coder** [comment]
Should we put it here instead of the footer?

![image](https://cloud.githubusercontent.com/assets/9070608/16253091/17344f8e-3866-11e6-8abe-b3e34265057d.png)

**Comment by damithc** [comment]
Not important enough to put on the title bar.
