### ISSUE TITLE
csv log file is messed up by commas in the log message

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#245]
![image](https://cloud.githubusercontent.com/assets/1673303/16142160/8d95b2aa-3495-11e6-9fe4-af7989785509.png)

**Comment by m133225** [comment]
Isn't there a way to treat make excel treat `'...'` as a string? Haven't tried it yet, but that should solve the problem if there is.

**Comment by damithc** [comment]
I think there is a standard way to specify a csv field that contains commas (some escape char?). I know we managed to solve this problem in TEAMMATES although I forget how.
