### ISSUE TITLE
Make Sync's datatypes implement ReadOnlyX interfaces from Model.

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#246]
Right now Sync component has to convert `CloudPerson` into `Person` for the response to the model component.

The `ReadOnlyX` interfaces have been changed so that the methods returning javaFX properties/observablelists are now optional. (Won't have to use `Property` or `ObservableList` in implementation).

If `CloudPerson` is made to inherit from `ReadOnlyPerson`, Sync can pass that `CloudPerson` directly to the Model without conversion. In the cloud response, model only needs `ReadOnlyPerson` functionality so there is no danger of mutating the fields in actual `CloudPerson`.

- `CloudPerson` should implement method signatures in `ReadOnlyPerson`.
- `CloudAddressBook` should implement `ReadOnlyAddressBook`.
- `List<CloudPerson>` can be easily converted to `List<ReadOnlyPerson>` using `Collections.unmodifiableList` to fulfil list getter methods (like in `ReadOnlyAddressBook`).
- The response sent to the model component will not need conversion to a `Person`, so Sync never has to know the `model.datatype.person.Person` class.

**Comment by m133225** [comment]
Actually, I think the conversion should be kept, in order to simulate the way we convert from `GitHub`'s representation of the object into our own representation. This should be part of the `CloudService`'s job to interpret the data given by the cloud (in `CloudPerson`) and converting it into a local model's `Person`.

**Comment by YijinL** [comment]
Will we be converting github's response into `CloudPerson`s first before converting again to a `ReadOnlyPerson`? Or we will parse github's response directly into `Person`s and pass it directly to model?

**Comment by m133225** [comment]
The latter.
The `CloudPerson` is the representation of the person object by the cloud (similar to how GitHub has it own representation of an `Issue`).
The `CloudService` will deal with the parsing of the `CloudSimulator`'s `RawCloudResponse`s into the Cloud's representation (`CloudPerson`), and then converting and returning it as a `Person` to the model. This is similar to how we read an input stream from the `HttpURLConnection`, then convert it into a `TurboIssue` in HT.

Note that the class names may seem confusing here, have changed them in my latest PR.
