### ISSUE TITLE
A git tracked file gets modified during full test run

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#254]
If I run all tests using the IDE, one of the git tracked file get edited during the test run.

**Comment by HansNewbie** [comment]
In my machine that would be the `TEMP_ADDRESSBOOK` file. It's the storage file. We should untrack and ignore it.

**Comment by damithc** [comment]
In my machine it is a different file.

**Comment by YijinL** [comment]
What file is it? This commit might have fixed it: 0a9d3d18401336a184fa5cbccbf975d7f63340dc

**Comment by damithc** [comment]
No longer happening.
