### ISSUE TITLE
Convert preference storage to json format

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#266]
This way, it will be more visible and easier to reduce configuration leaks between tests.
Although java has a Preferences API, it doesn't seem to be well developed beyond simply key/value pairs.

**Comment by damithc** [comment]
@HansNewbie can do this?

**Comment by HansNewbie** [comment]
Sure.

**Comment by HansNewbie** [comment]
Will this interfere with #265?

**Comment by damithc** [comment]
#265 merged.
