### ISSUE TITLE
Open file bug

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#27]
StorageManager's constructor does not initialise the modelManager field.
[modelManager is therefore always null.]
(https://github.com/HubTurbo/addressbook/blob/aad203a0069d618d6703a17ff9d774252960ff48/src/main/java/address/storage/StorageManager.java#L18-L23)

`loadPersonDataFromFile` will always crash with NPE.
`handleLoadDataRequestEvent` [silently absorbs the NPE](https://github.com/HubTurbo/addressbook/blob/aad203a0069d618d6703a17ff9d774252960ff48/src/main/java/address/storage/StorageManager.java#L63) and fires off a `FileOpeningExceptionEvent` 

causes problems with Ctrl-O.

**Comment by damithc** [comment]
@YijinL Are you fixing this? If you have fixed it already, create a PR for it.
