### ISSUE TITLE
Streamline TagSelectionEditDialogModel with ModelManager

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#281]
The place/workflow for the `TagSelectionEditDialogModel` class needs to be relooked at. 
At the moment it depends on `EventManger` which is usually reserved for `*Manager` classes.

**Comment by m133225** [comment]
Don't think this should be related to `ModelManager` since it is more like a state of the dialog. Will attempt to bind the view to the search results instead of raising events.
