### ISSUE TITLE
Filtering broken

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#285]
Filtering doesn't seem to work anymore.

**Comment by HansNewbie** [comment]
I just tried and it is already broken in V0.0.2. Going to try even older commits.

**Comment by yl-coder** [comment]
I think @m133225 is doing this one.

This is broken when the viewableperson was implemented i think.

**Comment by HansNewbie** [comment]
Noted. I will leave it to @m133225 to investigate then.

**Comment by m133225** [comment]
Oops, forgot to mention this issue in the PR for auto-closing. Fixed in #290.
