### ISSUE TITLE
Add a full system test

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#289]
In the first round, we can simply start the full app -- as similar to user environment as possible -- and do some ui tasks (no need to verify anything).
We can add verifications later.

**Comment by damithc** [comment]
@m133225 can do this one?

**Comment by m133225** [comment]
Is this supposed to just randomly perform UI tasks?

**Comment by damithc** [comment]
Yes, that would be the simplest first version.

**Comment by damithc** [comment]
@m133225 you are doing this right?

**Comment by m133225** [comment]
Yes, will be working on this.
