### ISSUE TITLE
Storage is coupled to Model

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#296]
Storage is currently calling ModelManager's resetData method directly when handling `LoadDataRequestEvent`. 

Contrast with Sync component which does similar operations on the model but does not couple itself to the model.

**Comment by damithc** [comment]
We can pass the callback method of ModelManager to storage using the event? Can be done later.

**Comment by damithc** [comment]
@YijinL if you are doing this, you can also inherit from `ComponentManger` at the same time.
