### ISSUE TITLE
Support a 'view documentation' menu linked to F1

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#309]
This feature will need to load a different version of the page based on if the product is stable, early access, or bleeding edge (i.e. master).

**Comment by damithc** [comment]
Let's put this on hold for a bit. I'm not sure if an online user manual is a good idea -- it's not a general solution.

**Comment by damithc** [comment]
Perhaps we can create help docs as html files (local) and use a help window (based on webview) to view it? @m133225 @YijinL @HansNewbie

**Comment by HansNewbie** [comment]
How about using some static site generator (like [Jekyll](https://jekyllrb.com/))? Write the docs in markdown and use the generator to output as HTML. Not sure how hard to setup though.

There is [JBake](http://jbake.org/) for Java.

**Comment by HansNewbie** [comment]
Otherwise we can create html files, too, if that's simpler.

**Comment by damithc** [comment]
If we go this way, let's start with plain html. We can add a generator later, if needed. The generator can be totally independent from the rest of the code base.

**Comment by damithc** [comment]
As discussed, we'll use a local copy of the user docs (i.e. not online documentation).
