### ISSUE TITLE
Crash at application start method when file path preference not set

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#31]
This happens when the Preferences registry entry for the user's file name does not exist.

Stepping through reveals that at [this line](https://github.com/HubTurbo/addressbook/blob/814cbd59abd20886d0ccbcf6251109ce77c6a436/src/main/java/address/MainApp.java#L33), `dataFromFile` is `null` so an NPE is thrown.

I've also discovered many other problems caused because `PreferencesManager`'s method `getPersonFilePath` can return null. There are 8 usages for this method and some of them already do not handle the null case properly.

Also, since the method returns type is `File`, most callers just pass the result of `getPersonFilePath` directly to other methods for processing, and the null case often gets overlooked, causing lots of errors. [Example in StorageManager](https://github.com/HubTurbo/addressbook/blob/814cbd59abd20886d0ccbcf6251109ce77c6a436/src/main/java/address/storage/StorageManager.java#L77)

Is there a better way to track that the user has no default file chosen? @damithc @ndt93 @dariusf

**Comment by YijinL** [comment]
Using Optional seems like the obvious way, because you will be forced to unwrap the value before passing it to other callees.

**Comment by damithc** [comment]
In the current form, the app cannot function fully unless there is a file. So, the method can return a default file (e.g. data.xml) if the variable is not set.
