### ISSUE TITLE
Memory leak when opening new file

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#318]
Noticeable only if the previous file is big.
1. Can add more debug log messages and run in debug mode.
2. Can use a profiler tool such as JProfiler

**Comment by damithc** [comment]
This may be useful (I took this allocation graph snapshot during the memory leak):
![image](https://cloud.githubusercontent.com/assets/1673303/16377531/2cb9c8ac-3c99-11e6-9895-72e949684e48.png)

**Comment by damithc** [comment]
Invocation stats:
![image](https://cloud.githubusercontent.com/assets/1673303/16377647/e6ab05f0-3c99-11e6-82e7-1eccc55a22a1.png)

**Comment by m133225** [comment]
Couple of things I could extract from some debugging:
- Each time a new file is loaded, the persons data are removed 1 by 1 (which is seen in `FilteredList` as it receives these changes 1 by 1 in `sourceChanged`).
- Each removal causes the list view to refresh. Therefore, if the screen displays 5 items, each removal will cause the list view to refresh up to 5 times

**Comment by m133225** [comment]
Should be fixed in `78f53ae`.

**Comment by damithc** [comment]
Yes, seems to be fine now.
