### ISSUE TITLE
Gui tests on Windows: Only partial GUI is visible

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#333]
Browser and the title bar is missing

**Comment by damithc** [comment]
@yl-coder may be you can help debug this issue? We need to find out at what point exactly the part of ui goes missing. Perhaps strip out the browser entirely and incrementally add back the missing stuff to find out at what point a part of the ui goes missing?

**Comment by damithc** [comment]
I found that our MainController sets the initial width to 340. I think textFx uses that to set the window size and fails to increase it later.

**Comment by yl-coder** [comment]
@damithc ok, i will look into this.

**Comment by yl-coder** [comment]
@damithc You're right. That's the problem.
