### ISSUE TITLE
Updates to a person does not show up on UI

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#35]
![screen shot 2016-05-11 at 12 55 12 pm](https://cloud.githubusercontent.com/assets/12193772/15170366/9fc7f43c-1777-11e6-892d-f3f22c4debdc.png)
Opening the person's info again shows the updated groups, but this is not reflected in the listview. This also applies to any other information. Re-filtering will help to refresh and show the updated information.

**Comment by damithc** [comment]
Yes, it seems add/delete is observable but edits are not. @acruis was trying to fix it earlier.

**Comment by acruis** [comment]
Aside from re-filtering, you can also simply scroll the person info card out of view and then back into view again. Happens because there's no binding between properties of Person objects and the label text properties in the person info card. See #18 for a solution.

**Comment by YijinL** [comment]
Same cause #12
