### ISSUE TITLE
Determine a suitable initial size for the Stage

### ISSUE THREAD

**Issue by yl-coder** [HubTurbo/addressbook#367]
As per title.

Continuation from #366, #333

**Comment by yl-coder** [comment]
I would suggest setting the initial size based on the screen size. Perhaps 70% of the screen height and 50% of the screen width? However depending of the screen ratio, different screen may give odd ratio of the app size. Maybe we could just handle two scenario now, wide and 4:3 screen.

@damithc any suggestions?

**Comment by damithc** [comment]
We can try that. However, another complementary feature is to remember the size next time user opens it. That way, user can tweak the size to fit their own preference.

**Comment by damithc** [comment]
We'll do a minimal implementation of this now. May be save the size only. Saving other attributes can be one in a later release.
