### ISSUE TITLE
When saving as a new file, data in the file is not propagated to the server

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#400]
The new addressbook is created on the cloud, but the existing data in the addressbook is not added to the cloud.

However, note that if this issue is solved, saving-as a large file will probably lead to usages of large number of API quota as each data has to be created **individually**, with each costing 1 API quota.
e.g. saving-as `scalabilitydata.xml` will immediately use 1000 API quota.

**Comment by damithc** [comment]
We need to consider the semantics of the 'save as' feature. In HT, there is no such feature.

**Comment by m133225** [comment]
At the moment, saving-as is assumed to be creating a whole new addressbook on the cloud. This will be the case until we introduce a `name` field for addressbook.

**Comment by damithc** [comment]
No longer applicable as we are removing the save as feature.
