### ISSUE TITLE
Selection is lost during syncing

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#41]
The selection (dark blue) is lost during syncing.

**Comment by YijinL** [comment]
It happened because when new data comes in from the mirror the current list gets replaced by that new data

**Comment by YijinL** [comment]
To be changed:

1. Person equality will use first and last name
2. Group equality uses name and checks from `Person.equals`
3. Loading data from files (mirror and main) will terminate and show an error message if duplicates are detected in the files. (No clear protocol for handling duplicates, eg which one to choose?)
4. Syncing will diff the incoming data with current state and update accordingly (add, delete, update)
