### ISSUE TITLE
Repeated app resizing fails

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#456]
At least on Mac, it will correctly maximize and reset to default size the first 2 times the key combination is pressed. 
However, from then on it will remain at the same default size (with some vertical movement every 2 times the keys are pressed).

Possible solution: http://stackoverflow.com/questions/18998671/set-height-and-width-of-stage-and-scene-in-javafx
```
protected void setDefaultSize() {
        primaryStage.setMaximized(false);
        primaryStage.setIconified(false);
        primaryStage.hide();
        primaryStage.show();
}
```
works, but causes flinching of the app.

**Comment by damithc** [comment]
Works on Windows. Seems a Mac-specific problem. Sure, try the s/o solution.
