### ISSUE TITLE
Updater stuck at 'Finalizing updates' during manual testing

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#461]
During manual testing, the footer status bar stays stuck at 'Finalizing updates'.
OS: Windows
![image](https://cloud.githubusercontent.com/assets/1673303/16682219/eb58d7cc-452b-11e6-818e-075d14899ba8.png)

**Comment by yl-coder** [comment]
Most likely the updater abort due to an exception and never executing the UpdaterCompletedEvent.

**Comment by damithc** [comment]
Yes, you may be right. I found this in the log. Error handling needs to improve.

Exception in thread "pool-7-thread-2" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.nio.file.Files.copy(Files.java:2984)
	at address.updater.UpdateManager.extractJarUpdater(UpdateManager.java:295)
	at address.updater.UpdateManager.checkForUpdate(UpdateManager.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by HansNewbie** [comment]
This problem will be present in development only because `JarUpdater` is not tracked in git (as its binary will be generated at every release), hence the `JarUpdater` resource will not be present if not created first.

**Comment by damithc** [comment]
Perhaps the code can use some trick to identify if it is the dev env? or, can we put a fake jar file in the dev env? The latter is better because it doesn't pollute the production code.

**Comment by HansNewbie** [comment]
The former can be done by checking if the app is run from JAR file (I think
it's in `FileUtil.isRunFromJar()`). Dev env is not running from JAR.

I am not sure about the latter using fake JAR, but you can always generate
the real one by running `createJarUpdater` gradle task.

**Comment by damithc** [comment]
If it is checking for the existence of the jar file, we can put a dummy jar file (empty) with the correct name and add it to git. That way, the code can remains the same.

**Comment by yl-coder** [comment]
So no need to handle the exception where the jar file is not there?

**Comment by HansNewbie** [comment]
It's better to have more checks.
