### ISSUE TITLE
Typing in the browser also fires the accelerators

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#486]
Try logging into GitHub on the app 😛

**Comment by yl-coder** [comment]
One way is to disable the accelerators when the browser is in focus, which also means user need to click on other part of the app to start using shortcuts. Should we do that?

**Comment by damithc** [comment]
Yes, I'm ok for disabling keybindings (not just accelerators) when the browser is in focus. That will avoid conflicts with the bindings used by the webpage. 
However, we may not want to disable all bindings e.g. global hotkeys
See if there is an elegant way to disable specific (or all) accelerators. They are the ones harder to control.
