### ISSUE TITLE
jarUpdater is not being updated

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#499]
Not 100% sure, am checking with @HansNewbie.
Probably not too big of an issue since we probably won't change it too much, but we should consider including it in the updates if this is to be a model application.

**Comment by damithc** [comment]
If we need to update the jarUpdater and the updater cannot do that automatically, we'll have to inform users to download the new version of the jarUpdater using some other means e.g. using the `tip of the day` feature

**Comment by m133225** [comment]
This has been resolved in the update architecture change.
