### ISSUE TITLE
Add full GUI testing for tagging

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#559]
Test both the accelerator method and within the person edit dialog.

**Comment by damithc** [comment]
@m133225 can do this?

**Comment by m133225** [comment]
Isn't the testing for accelerators done in `KeyBindingsGuiTest` already?

**Comment by damithc** [comment]
Yes. You can add/enhance the corresponding Gui unit tests at the same time.

**Comment by m133225** [comment]
There's something similar (but not using shortcut to open the tag selection dialog) in `FullSystemTest`. Should remove that scenario from that class?

**Comment by damithc** [comment]
Yes, fullsystemtest should be removed after moving its parts to other
classes.
>
>

-- 
Sent from a mobile device.

**Comment by damithc** [comment]
I noticed at least one bug in the tagging feature. Let's see if the Gui test uncovers it. :-)
