### ISSUE TITLE
PersonCardHandle::isShowingGracePeriod fails sometimes

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#565]
Seems to fail when performing edits on a person other than alice.
- `isPendingStateRootVisible()` returns `false` instead of the required `true`

**Comment by damithc** [comment]
We are taking screenshots right? What does the screenshot show? May be the grace period is too short?

**Comment by m133225** [comment]
The pending label is there, similar to when the edit is made on `alice` but the method incorrectly returns a `false` if the edits are made on a different person. (tried on both `benson` and `charlie`)

**Comment by yl-coder** [comment]
I know what's wrong. Fixed it in the latest PR
