### ISSUE TITLE
Clear listview selection model after deletion 

### ISSUE THREAD

**Issue by yl-coder** [HubTurbo/addressbook#571]
After single or multiple delete, the selections are passed on to its neighbour. Need to clear listview selection index upon successful deletion.

**Comment by m133225** [comment]
Not sure if this is considered a bug? From a user's POV, it would be a more fluent workflow.

**Comment by yl-coder** [comment]
Hmm for me, it seems unnatural to have the selection on other user after the selected user is deleted. It still alright if it is only one deletion, but multiple deletion(select second and fourth card) just look really odd. 

After checking several application, seems like the normal convention is to clear the selection index. 
E.g. Window File explorer, Google contacts, etc.

**Comment by damithc** [comment]
I prefer to select the next card in the list, which makes it easier for the user to process a list sequentially. However, we should not select multiple items automatically. Instead, select one card that we suspect the one user will want to work with next.
