### ISSUE TITLE
Add a component for handling keyboard shortcuts

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#60]
Try to keep the keyboard shortcuts in one place

**Comment by YijinL** [comment]
Some keyboard shortcuts are declared and embedded in the `fxml` view files. See [RootLayout.fxml](https://github.com/HubTurbo/addressbook/blob/f080b2c27d65b54124292c8f8e9778763a268d5d/src/main/resources/view/RootLayout.fxml#L17-L20) for an example.

Should they be moved out of those files and set programmatically?

**Comment by damithc** [comment]
Yes, I'm planning to move them to one place if that's possible.
