### ISSUE TITLE
App crashes at exit

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#61]
Freezes when I use the 'Exit' menu option.

**Comment by YijinL** [comment]
Removing [this line](https://github.com/HubTurbo/addressbook/blob/d1cb166368e23d5e9ce5c17925ae9b0d96d3d3fa/src/main/java/address/controller/MainController.java#L73) fixes `System.exit(0)` hanging.

@yl-coder do you have any idea why? Maybe some shutdown hooks in jxbrowser?

**Comment by yl-coder** [comment]
Ok, i will check it out.
