### ISSUE TITLE
Exiting app quickly after making changes causes next run to fail load from mirror file

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#66]
`org.xml.sax.SAXParseException;  lineNumber: 1; columnNumber: 1; Premature end of file.`
Probably the file pointer has not been rewound?

Reproduce:

1. open app
2. delete a random person (or any other change)
3. **immediately** close the app through the corner <kbd>X</kbd>
4. reopen the app, everything should be wiped

Should we implement some form of waiting for file operations to complete in the `MainApp.close()` method?

**Comment by yl-coder** [comment]
I guess this is fixed?

**Comment by YijinL** [comment]
Hotfixed but unsure how to fix it nicely

**Comment by damithc** [comment]
Still happening?
