### ISSUE TITLE
Support contact groups/labels

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#9]
- Each instance of `ModelManager` has to maintain a list of groups
- `PersonOverview.fxml` and `PersonEditDialog.fxml` to reflect the person's assigned `ContactGroup`

**Comment by damithc** [comment]
To clarify, this should be very similar to github labels. For example, the labels can be `Friends`, `Colleagues`, `Relatives` and the same person can be a `Friend` as well as a `Colleague`
