### ISSUE TITLE
Make the cloud's API similar to GitHub's

### ISSUE THREAD

**Issue by m133225** [HubTurbo/addressbook#94]
We now send all data to the cloud for processing, which performance gets worse as the addressbook becomes bigger. Also, this is unlike the GitHub's API which we are trying to emulate for HT.

This will also bring in the desired purpose of #8 - which includes showing pending elements statuses

**Comment by m133225** [comment]
I've built another project just to test and understand `egit`'s API (still in progress).

- Seems like `editLabels` in `egit`'s `LabelService` is not working.

- Also, from [GitHub's API Documentation](https://developer.github.com/v3/issues/labels/#update-a-label), it is using HTTP `PATCH` which is unsupported by the default library `HttpURLConnection` ([bug](http://stackoverflow.com/questions/25163131/httpurlconnection-invalid-http-method-patch)). Tried many ways to work around this, but can't seem to do so. Will look into potential http libraries (possibly `Apache httpclient`) after looking through the other API.

**Comment by damithc** [comment]
Good idea to test it out separately. We should definitely have our own API that wraps around eGit.

**Comment by m133225** [comment]
After looking through and understanding the key APIs, I think that while we are able to make use of the [Event API](https://developer.github.com/v3/activity/events/) with the following [Events Types](https://developer.github.com/v3/activity/events/types/), there is not much benefits to doing so:

Neutral:
- Events (or rather, the API in general) also **do no support retrieving only updates of the resources**. Therefore, we have to make use of their API to do a (full) manual check on the resources once in a while. Even then, we have to handle label changes by comparing old lists and new lists of labels, and manually modifying the affected issues. The alternative would be to re-download the whole repository again, which is not very practical.

Cons:
- The logic has to be able to resolve these events, which may complicate the design
- It may consume more API than how HT has implemented it (Since we have to download 2 events in the case where the user changed an issue's labels twice before updating).

However, I think that are areas where the current HT implementation can be improved such as updating of issues where we can reduce the API usage. Will implement a similar interaction with the cloud for `addressbook`

**Comment by damithc** [comment]
@m133225 can you add to the GoogleDoc (below CloudApi) the GitHubApi you think we can have? (i.e. the one CloudApi will be mimicking)

**Comment by m133225** [comment]
Hmm, but how close should we mimic the API? We could either provide a high-level API which immediately returns the important data, or we could communicate with the cloud (similarly to how 'EGit' does it) using a modified 'HttpURLConnection' where the cloud responses to its 'openConnection' and returns details like page headers and server response code i.e. 404.

**Comment by damithc** [comment]
I'm thinking of a high level blocking API that hides the cloud communication. It will use eGit internally. e.g.
`List<Issue> getRecentlyModifiedIssues(Time from, Time to) : returns issues modified during the specified period. No quota will be used if no issues were modified during that period.`
In the example above, we can use a more sophisticated return value to contain other data e.g. remaining quota

**Comment by m133225** [comment]
I think an

**Comment by m133225** [comment]
Then I think `Optional<InputStream>` would be suitable here. `Optional` because it may be a "network error" and `InputStream` is how `GitHub` returns its data in `JSON` format. Will come up with the API asap.
